# SPDX-FileCopyrightText: 2022 mirrorcult <lunarautomaton6@gmail.com>
# SPDX-FileCopyrightText: 2024 SlamBamActionman <83650252+SlamBamActionman@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 TsjipTsjip <19798667+TsjipTsjip@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 deathride58 <deathride58@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 lzk <124214523+lzk228@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 slarticodefast <161409025+slarticodefast@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 Aiden <28298836+Aidenkrz@users.noreply.github.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

"🎨 Изменения: Спрайты":
- changed-files:
  - any-glob-to-any-file: '**/*.rsi/*.png'

"🗺️ Изменения: Карты":
- changed-files:
  - any-glob-to-any-file:
    - 'Resources/Maps/**/*.yml'
    - 'Resources/Prototypes/Maps/**/*.yml'

"🖼️ Изменения: UI":
- changed-files:
  - any-glob-to-any-file: '**/*.xaml*'

"🔮 Изменения: Шейдеры":
- changed-files:
  - any-glob-to-any-file: '**/*.swsl'

"🎵 Изменения: Аудио":
- changed-files:
  - any-glob-to-any-file: '**/*.ogg'

"⚙️ Изменения: No C#":
- changed-files:
  # Equiv to any-glob-to-all as long as this has one matcher. If ALL changed files are not C# files, then apply label.
  - all-globs-to-all-files: "!**/*.cs"
